const data = {
  products: [
    {
      name: "Rockwell Automation’s Retro Encabulator",
      slug: "rockwellautomation’s-retro-encabulator",
      price: 299,
      imgUrl: "productImages/Rockwell-Automation-Retro-Encabulator.png",
      inStock: true,
      description: "Super dope tell all your friends about it",
      quantity: 28,
      category: "A",
      rating: 8,
      numReviews: 9,
    },
    {
      name: "3000 Netse Land Parcel",
      slug: "3000-netse-land-parcel",
      price: 99999,
      imgUrl: "productImages/3000-Netse-Land-Parcel.png",
      inStock: true,
      description: "totally rad your friends moms will love you",
      quantity: 10,
      category: "B",
      rating: 10,
      numReviews: 9,
    },
    {
      name: "3761 Tarma Beemoa Truck",
      slug: "3761-tarma-beemoa-truck",
      price: 199,
      imgUrl: "productImages/3761-Tarmac-Beemoa-Truck-(9982111-miles).png",
      inStock: false,
      description: "Doesn't hold your emotional baggage",
      quantity: 15,
      category: "C",
      rating: 9,
      numReviews: 7,
    },
    {
      name: "3987 Miola Tantu",
      slug: "3987-miola-tantu",
      price: 2999,
      imgUrl: "productImages/3987-Miola-Tantu-(9857700-miles).png",
      inStock: true,
      description: "Great Vehicle , driven it for eons",
      quantity: 1,
      category: "A",
      rating: 7,
      numReviews: 6,
    },
  ],
};
export default data;
