import React from 'react'
import styled from "styled-components"

const Body = styled.div`
background-color: #1F2041;
color: gold;
text-shadow: 3px 3px 2px black;
display: flex;
flex-direction: column;
`
const Title = styled.h1`
margin: 20px;
`

const RightBlock = styled.div`
background-color: #53546F;
margin: 20px;
margin-top: 0px;
margin-bottom: 0px;
padding: 20px;
display: flex;
flex-direction: column;
position: relative;
`;
const DescriptionBlock = styled.div`
color: aqua;
`
const PictureAndRightBlock = styled.div`
display: flex;
flex-direction: row;
`;
const Img = styled.img`
width: 40vw;
border-radius: 10px;
`
const AddToCart = styled.button`
background-color: #53546F;
color: white;
width: 15vw;
height: 3vw;
font-size: 2vw;
position: absolute;
bottom: 20px;
right: 20px;
border: 2px solid gold;
color: gold;
`
const Rating = styled.div`
width: 20vw;
align-self: center;
display: flex;
flex-direction: column;
justify-items: center;
align-items: center;
margin: 30px;
padding: 10px;
gap: -100px;
text-shadow: 5px 5px 2px black;
`
const Stars = styled.div`
margin-bottom: 10px;
font-size: 3rem;
`

function SingleProduct() {
  return (
    <Body>
      <Title>Product Title: Retro Encabulator by Rockwell Automation</Title>
      <PictureAndRightBlock>
        <Img src="productImages/Rockwell-Automation-Retro-Encabulator.png"></Img>
        <RightBlock>
          <DescriptionBlock>
            <h3>Product Description</h3>
            <p>Our most popular product, the Retro Encabulator, by Rockwell Automation virtually eliminates sinusoidal depleneration! </p>
            <h4>Check out this description from the manufacturer: </h4>
            <p>Here at Rockwell Automation’s world headquarters, research has been
              proceeding to develop a line of automation products that establishes new
              standards for quality, technological leadership, and operating excellence. With customer success as our primary focus, work has been proceeding on the crudely conceived idea of an instrument that would not only provide inverse reactive current, for use in unilateral phase detractors, but would also be capable of automatically synchronizing cardinal grammeters. Such an instrument comprised of Dodge gears and bearings, Reliance Electric motors, Allen-Bradley controls, and all monitored by Rockwell Software is Rockwell Automation’s "Retro Encabulator".
              Now, basically the only new principle involved is that instead of power
              being generated by the relative motion of conductors and fluxes, it’s
              produced by the modial interaction of magneto-reluctance and capacitive diractance.
              The original machine had a base plate of prefabulated amulite, surmounted by a malleable logarithmic
              casing in such a way that the two spurving bearings were in a direct line with the panametric fan.
              The lineup consisted simply of six hydrocoptic marzelvanes, so fitted to the ambifacient lunar waneshaft
              that sidefumbling was effectively prevented. The main winding was of the normal lotus o-deltoid type placed
              in panendermic semiboloid slots of the stator, every seventh conductor being connected by a non-reversible
              tremie pipe to the differential girdlespring on the ‘up’ end of the grammeters. Moreover, whenever
              fluorescence score motion is required, it may also be employed in conjunction with a drawn reciprocation
              dingle arm to reduce sinusoidal depleneration.
              The Retro Encabulator has now reached a high level of development, and it’s being successfully used in the
              operation of milford trenions. It’s available soon; wherever Rockwell Automation products are sold.</p>
          </DescriptionBlock>
          <AddToCart>Add To Cart</AddToCart>
        </RightBlock>
      </PictureAndRightBlock>
      <Rating>
        <h3>Rating: </h3>
        <Stars>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>★</span>
          <span>10/10</span>
        </Stars>
      </Rating>
    </Body>
  )
}

export default SingleProduct